export type ChannelCommandSurface = "desktop" | "weixin" | "cli";
export type ChannelCommandOutputPolicy =
  | "result-first"
  | "review-gated"
  | "status-first"
  | "control-reply";
export type ChannelCommandMemoryPolicy =
  | "store-result-only"
  | "review-gated-source"
  | "never-store"
  | "transient";
export type ChannelCommandActiveSessionPolicy =
  | "execute-now"
  | "queue-next"
  | "interrupt-current"
  | "status-only";

export interface ChannelCommandDefinition {
  readonly id: string;
  readonly canonicalName: string;
  readonly aliases: readonly string[];
  readonly surfaces: readonly ChannelCommandSurface[];
  readonly description: string;
  readonly argsHint: string;
  readonly outputPolicy: ChannelCommandOutputPolicy;
  readonly memoryPolicy: ChannelCommandMemoryPolicy;
  readonly activeSessionPolicy: ChannelCommandActiveSessionPolicy;
}

export interface ChannelSlashCommandEnvelope {
  readonly commandId: string;
  readonly canonicalName: string;
  readonly matchedName: string;
  readonly args: string;
  readonly outputPolicy: ChannelCommandOutputPolicy;
  readonly memoryPolicy: ChannelCommandMemoryPolicy;
  readonly activeSessionPolicy: ChannelCommandActiveSessionPolicy;
}

const ALL_SURFACES: readonly ChannelCommandSurface[] = ["desktop", "weixin", "cli"];

const CHANNEL_COMMAND_REGISTRY: readonly ChannelCommandDefinition[] = [
  {
    id: "production.start",
    canonicalName: "制作",
    aliases: [
      "生产",
      "创建",
      "生成",
      "导演",
      "脚本",
      "剧本",
      "文案",
      "director",
      "production",
      "script",
      "screenplay",
      "copywriting",
    ],
    surfaces: ALL_SURFACES,
    description: "创建 Director 制作任务，并以结果优先方式回复用户。",
    argsHint: "<制作目标>",
    outputPolicy: "result-first",
    memoryPolicy: "store-result-only",
    activeSessionPolicy: "execute-now",
  },
  {
    id: "media.comfyui.run",
    canonicalName: "ComfyUI",
    aliases: ["comfy", "comfy-ui", "本地出图", "工作流出图"],
    surfaces: ALL_SURFACES,
    description: "通过已配置 ComfyUI 外部工具提交真实 workflow，并返回生成产物。",
    argsHint: "<提示词>",
    outputPolicy: "result-first",
    memoryPolicy: "never-store",
    activeSessionPolicy: "execute-now",
  },
  {
    id: "learning.admit",
    canonicalName: "学习",
    aliases: ["learn", "吸收", "研究", "资料"],
    surfaces: ALL_SURFACES,
    description: "从链接、文件、目录、主题或粘贴文本生成待审经验候选。",
    argsHint: "<链接|路径|主题|文本>",
    outputPolicy: "review-gated",
    memoryPolicy: "review-gated-source",
    activeSessionPolicy: "execute-now",
  },
  {
    id: "learning.directory",
    canonicalName: "从目录学习",
    aliases: ["学习 目录", "目录学习", "learn directory"],
    surfaces: ["desktop", "cli"],
    description: "从本地目录读取资料，生成待审经验候选。",
    argsHint: "<目录路径>",
    outputPolicy: "review-gated",
    memoryPolicy: "review-gated-source",
    activeSessionPolicy: "execute-now",
  },
  {
    id: "learning.url",
    canonicalName: "从URL学习",
    aliases: ["学习 URL", "学习链接", "learn url"],
    surfaces: ALL_SURFACES,
    description: "从网页链接抓取资料，生成待审经验候选。",
    argsHint: "<url>",
    outputPolicy: "review-gated",
    memoryPolicy: "review-gated-source",
    activeSessionPolicy: "execute-now",
  },
  {
    id: "learning.query",
    canonicalName: "从主题学习",
    aliases: ["学习 主题", "网页主题学习", "learn query"],
    surfaces: ALL_SURFACES,
    description: "围绕搜索主题收集资料，生成待审经验候选。",
    argsHint: "<主题>",
    outputPolicy: "review-gated",
    memoryPolicy: "review-gated-source",
    activeSessionPolicy: "execute-now",
  },
  {
    id: "experience.list",
    canonicalName: "经验列表",
    aliases: ["经验", "经验 列表", "经验库", "list experience"],
    surfaces: ALL_SURFACES,
    description: "查看经验候选、已收录经验和审查状态。",
    argsHint: "[分类|标签|状态]",
    outputPolicy: "status-first",
    memoryPolicy: "never-store",
    activeSessionPolicy: "status-only",
  },
  {
    id: "experience.view",
    canonicalName: "查看经验",
    aliases: ["经验 查看", "经验详情", "view experience"],
    surfaces: ALL_SURFACES,
    description: "打开一条经验的完整原文、提炼结果、来源和审查记录。",
    argsHint: "<experienceId>",
    outputPolicy: "status-first",
    memoryPolicy: "never-store",
    activeSessionPolicy: "status-only",
  },
  {
    id: "experience.accept",
    canonicalName: "接受经验",
    aliases: ["经验 接受", "经验 通过", "经验 审核通过", "accept experience"],
    surfaces: ALL_SURFACES,
    description: "人工通过待审经验候选，允许进入提炼或晋升流程。",
    argsHint: "<candidateId>",
    outputPolicy: "control-reply",
    memoryPolicy: "never-store",
    activeSessionPolicy: "execute-now",
  },
  {
    id: "experience.reject",
    canonicalName: "拒绝经验",
    aliases: ["经验 拒绝", "经验 丢弃", "reject experience"],
    surfaces: ALL_SURFACES,
    description: "拒绝低质量、重复、跑题或不安全的经验候选。",
    argsHint: "<candidateId> [原因]",
    outputPolicy: "control-reply",
    memoryPolicy: "never-store",
    activeSessionPolicy: "execute-now",
  },
  {
    id: "experience.promote",
    canonicalName: "晋升经验",
    aliases: ["经验 晋升", "经验 提炼", "提炼经验", "promote experience"],
    surfaces: ALL_SURFACES,
    description: "把已接受经验提炼为知识候选或可复用 Skill 候选。",
    argsHint: "<experienceId>",
    outputPolicy: "review-gated",
    memoryPolicy: "review-gated-source",
    activeSessionPolicy: "execute-now",
  },
  {
    id: "experience.classify",
    canonicalName: "经验分类",
    aliases: ["经验 分类", "分类经验", "classify experience"],
    surfaces: ["desktop", "cli"],
    description: "为经验设置或调整分类，避免经验库混成一堆。",
    argsHint: "<experienceId> <分类>",
    outputPolicy: "control-reply",
    memoryPolicy: "never-store",
    activeSessionPolicy: "execute-now",
  },
  {
    id: "experience.tag",
    canonicalName: "经验打标",
    aliases: ["经验 标签", "经验 打标", "tag experience"],
    surfaces: ["desktop", "cli"],
    description: "为经验添加、删除或重算标签。",
    argsHint: "<experienceId> <标签...>",
    outputPolicy: "control-reply",
    memoryPolicy: "never-store",
    activeSessionPolicy: "execute-now",
  },
  {
    id: "experience.fromRunReport",
    canonicalName: "运行沉淀经验",
    aliases: ["经验 从运行", "复盘成经验", "run report experience"],
    surfaces: ["desktop", "cli"],
    description: "把一次制作运行的结果、反馈和复盘转成待审经验候选。",
    argsHint: "<runId>",
    outputPolicy: "review-gated",
    memoryPolicy: "review-gated-source",
    activeSessionPolicy: "execute-now",
  },
  {
    id: "experience.fromTraceProposal",
    canonicalName: "轨迹沉淀经验",
    aliases: ["经验 从轨迹", "轨迹成经验", "trace experience"],
    surfaces: ["desktop", "cli"],
    description: "从执行轨迹中提取可复用做法，生成待审经验候选。",
    argsHint: "<traceId>",
    outputPolicy: "review-gated",
    memoryPolicy: "review-gated-source",
    activeSessionPolicy: "execute-now",
  },
  {
    id: "knowledge.candidates",
    canonicalName: "知识候选",
    aliases: ["知识 候选", "知识列表", "knowledge candidates"],
    surfaces: ALL_SURFACES,
    description: "查看待审知识候选及其来源经验。",
    argsHint: "[分类|标签|状态]",
    outputPolicy: "status-first",
    memoryPolicy: "never-store",
    activeSessionPolicy: "status-only",
  },
  {
    id: "knowledge.accept",
    canonicalName: "接受知识",
    aliases: ["知识 接受", "知识 通过", "accept knowledge"],
    surfaces: ALL_SURFACES,
    description: "接受知识候选，等待发布到运行时可召回知识库。",
    argsHint: "<candidateId>",
    outputPolicy: "control-reply",
    memoryPolicy: "never-store",
    activeSessionPolicy: "execute-now",
  },
  {
    id: "knowledge.reject",
    canonicalName: "拒绝知识",
    aliases: ["知识 拒绝", "reject knowledge"],
    surfaces: ALL_SURFACES,
    description: "拒绝不够稳定、不可复用或来源不足的知识候选。",
    argsHint: "<candidateId> [原因]",
    outputPolicy: "control-reply",
    memoryPolicy: "never-store",
    activeSessionPolicy: "execute-now",
  },
  {
    id: "knowledge.publish",
    canonicalName: "发布知识",
    aliases: ["知识 发布", "发布经验", "publish knowledge"],
    surfaces: ALL_SURFACES,
    description: "发布已接受知识包，让后续制作可召回。",
    argsHint: "<candidateId|packageId>",
    outputPolicy: "control-reply",
    memoryPolicy: "never-store",
    activeSessionPolicy: "execute-now",
  },
  {
    id: "knowledge.recallPreview",
    canonicalName: "知识召回预览",
    aliases: ["知识 召回", "召回预览", "recall preview"],
    surfaces: ALL_SURFACES,
    description: "按项目、分组、标签或目标预览会召回哪些知识。",
    argsHint: "<目标|标签|项目>",
    outputPolicy: "status-first",
    memoryPolicy: "never-store",
    activeSessionPolicy: "status-only",
  },
  {
    id: "knowledge.explain",
    canonicalName: "解释知识",
    aliases: ["知识 解释", "知识 来源", "explain knowledge"],
    surfaces: ["desktop", "cli"],
    description: "解释知识条目的来源、适用边界和召回理由。",
    argsHint: "<knowledgeId>",
    outputPolicy: "status-first",
    memoryPolicy: "never-store",
    activeSessionPolicy: "status-only",
  },
  {
    id: "knowledge.diff",
    canonicalName: "知识差异",
    aliases: ["知识 对比", "知识 diff", "diff knowledge"],
    surfaces: ["desktop", "cli"],
    description: "比较两个知识版本或候选的差异。",
    argsHint: "<leftId> <rightId>",
    outputPolicy: "status-first",
    memoryPolicy: "never-store",
    activeSessionPolicy: "status-only",
  },
  {
    id: "knowledge.rollback",
    canonicalName: "回滚知识",
    aliases: ["知识 回滚", "rollback knowledge"],
    surfaces: ["desktop", "cli"],
    description: "回滚已发布知识包到指定版本。",
    argsHint: "<knowledgeId|packageId> [version]",
    outputPolicy: "control-reply",
    memoryPolicy: "never-store",
    activeSessionPolicy: "execute-now",
  },
  {
    id: "skills.list",
    canonicalName: "Skill列表",
    aliases: ["技能", "技能 列表", "skill 列表", "skills"],
    surfaces: ALL_SURFACES,
    description: "查看内生 Skill、外部 Skill、分类和启用状态。",
    argsHint: "[分类|来源|状态]",
    outputPolicy: "status-first",
    memoryPolicy: "never-store",
    activeSessionPolicy: "status-only",
  },
  {
    id: "skills.proposeFromExperience",
    canonicalName: "从经验生成Skill",
    aliases: ["技能 从经验", "经验成skill", "skill from experience"],
    surfaces: ["desktop", "cli"],
    description: "把稳定经验提炼成待审 Skill 候选。",
    argsHint: "<experienceId>",
    outputPolicy: "review-gated",
    memoryPolicy: "review-gated-source",
    activeSessionPolicy: "execute-now",
  },
  {
    id: "skills.accept",
    canonicalName: "接受Skill",
    aliases: ["技能 接受", "skill 接受", "accept skill"],
    surfaces: ALL_SURFACES,
    description: "接受 Skill 候选，允许后续制作调用。",
    argsHint: "<candidateId>",
    outputPolicy: "control-reply",
    memoryPolicy: "never-store",
    activeSessionPolicy: "execute-now",
  },
  {
    id: "skills.reject",
    canonicalName: "拒绝Skill",
    aliases: ["技能 拒绝", "skill 拒绝", "reject skill"],
    surfaces: ALL_SURFACES,
    description: "拒绝不稳定、重复或边界不清的 Skill 候选。",
    argsHint: "<candidateId> [原因]",
    outputPolicy: "control-reply",
    memoryPolicy: "never-store",
    activeSessionPolicy: "execute-now",
  },
  {
    id: "skills.apply",
    canonicalName: "调用Skill",
    aliases: ["技能 调用", "技能 应用", "apply skill"],
    surfaces: ALL_SURFACES,
    description: "在当前制作目标或指定运行中调用一个 Skill。",
    argsHint: "<skillId> [目标|runId]",
    outputPolicy: "result-first",
    memoryPolicy: "store-result-only",
    activeSessionPolicy: "execute-now",
  },
  {
    id: "skills.classify",
    canonicalName: "Skill分类",
    aliases: ["技能 分类", "classify skill"],
    surfaces: ["desktop", "cli"],
    description: "调整 Skill 分类，区分内生 Skill 与外部 Skill。",
    argsHint: "<skillId> <分类>",
    outputPolicy: "control-reply",
    memoryPolicy: "never-store",
    activeSessionPolicy: "execute-now",
  },
  {
    id: "skills.tag",
    canonicalName: "Skill打标",
    aliases: ["技能 标签", "技能 打标", "tag skill"],
    surfaces: ["desktop", "cli"],
    description: "为 Skill 添加、删除或重算标签。",
    argsHint: "<skillId> <标签...>",
    outputPolicy: "control-reply",
    memoryPolicy: "never-store",
    activeSessionPolicy: "execute-now",
  },
  {
    id: "tools.list",
    canonicalName: "工具列表",
    aliases: ["工具", "工具 列表", "外部工具", "list tools"],
    surfaces: ALL_SURFACES,
    description: "查看外部 CLI、桌面工具和平台适配器的接入状态。",
    argsHint: "[分类|状态]",
    outputPolicy: "status-first",
    memoryPolicy: "never-store",
    activeSessionPolicy: "status-only",
  },
  {
    id: "tools.register",
    canonicalName: "注册工具",
    aliases: ["工具 注册", "添加工具", "register tool"],
    surfaces: ["desktop", "cli"],
    description: "注册新的外部工具或第三方平台适配器。",
    argsHint: "<name> <command|adapter>",
    outputPolicy: "control-reply",
    memoryPolicy: "never-store",
    activeSessionPolicy: "execute-now",
  },
  {
    id: "tools.enable",
    canonicalName: "启用工具",
    aliases: ["工具 启用", "enable tool"],
    surfaces: ["desktop", "cli"],
    description: "启用已注册工具，让制作流程可以路由调用。",
    argsHint: "<toolId>",
    outputPolicy: "control-reply",
    memoryPolicy: "never-store",
    activeSessionPolicy: "execute-now",
  },
  {
    id: "tools.disable",
    canonicalName: "停用工具",
    aliases: ["工具 停用", "disable tool"],
    surfaces: ["desktop", "cli"],
    description: "停用工具或平台适配器，保留配置但禁止调用。",
    argsHint: "<toolId>",
    outputPolicy: "control-reply",
    memoryPolicy: "never-store",
    activeSessionPolicy: "execute-now",
  },
  {
    id: "tools.capabilities",
    canonicalName: "工具能力",
    aliases: ["工具 能力", "平台能力", "能力", "help", "tool capabilities"],
    surfaces: ALL_SURFACES,
    description: "查看工具或平台能执行哪些能力、输入输出和权限边界。",
    argsHint: "[toolId|platformId]",
    outputPolicy: "status-first",
    memoryPolicy: "never-store",
    activeSessionPolicy: "status-only",
  },
  {
    id: "run.confirm",
    canonicalName: "确认",
    aliases: ["确认执行", "确认继续", "继续执行", "执行", "approve"],
    surfaces: ALL_SURFACES,
    description: "确认或继续当前待审制作运行。",
    argsHint: "[补充要求]",
    outputPolicy: "control-reply",
    memoryPolicy: "transient",
    activeSessionPolicy: "execute-now",
  },
  {
    id: "run.status",
    canonicalName: "运行状态",
    aliases: ["运行 状态", "run status"],
    surfaces: ALL_SURFACES,
    description: "查看指定 run 或当前活跃 run 的状态。",
    argsHint: "[runId]",
    outputPolicy: "status-first",
    memoryPolicy: "never-store",
    activeSessionPolicy: "status-only",
  },
  {
    id: "run.start",
    canonicalName: "启动运行",
    aliases: ["运行 启动", "start run"],
    surfaces: ["desktop", "cli"],
    description: "启动已创建的制作蓝图运行。",
    argsHint: "<blueprintId>",
    outputPolicy: "control-reply",
    memoryPolicy: "transient",
    activeSessionPolicy: "execute-now",
  },
  {
    id: "run.once",
    canonicalName: "执行一次",
    aliases: ["运行 一次", "run once"],
    surfaces: ["desktop", "cli"],
    description: "执行一次当前运行的下一步。",
    argsHint: "[runId]",
    outputPolicy: "control-reply",
    memoryPolicy: "transient",
    activeSessionPolicy: "execute-now",
  },
  {
    id: "run.continue",
    canonicalName: "继续运行",
    aliases: ["运行 继续", "继续推进", "continue run", "run continue"],
    surfaces: ALL_SURFACES,
    description: "继续当前或指定运行，批准待审环节并推进到下一个真实状态。",
    argsHint: "[runId]",
    outputPolicy: "control-reply",
    memoryPolicy: "transient",
    activeSessionPolicy: "execute-now",
  },
  {
    id: "run.pause",
    canonicalName: "暂停运行",
    aliases: ["运行 暂停", "pause run"],
    surfaces: ALL_SURFACES,
    description: "暂停当前或指定运行。",
    argsHint: "[runId]",
    outputPolicy: "control-reply",
    memoryPolicy: "transient",
    activeSessionPolicy: "interrupt-current",
  },
  {
    id: "run.resume",
    canonicalName: "恢复运行",
    aliases: ["运行 恢复", "resume run"],
    surfaces: ALL_SURFACES,
    description: "恢复已暂停运行。",
    argsHint: "[runId]",
    outputPolicy: "control-reply",
    memoryPolicy: "transient",
    activeSessionPolicy: "execute-now",
  },
  {
    id: "run.abort",
    canonicalName: "终止运行",
    aliases: ["运行 终止", "运行 停止", "停止运行", "停止", "abort run", "stop run"],
    surfaces: ALL_SURFACES,
    description: "终止当前或指定运行。",
    argsHint: "[runId] [原因]",
    outputPolicy: "control-reply",
    memoryPolicy: "transient",
    activeSessionPolicy: "interrupt-current",
  },
  {
    id: "run.report",
    canonicalName: "运行报告",
    aliases: ["运行 报告", "run report"],
    surfaces: ALL_SURFACES,
    description: "查看制作运行产物、审查项、调用经验与 Skill 命中情况。",
    argsHint: "<runId>",
    outputPolicy: "status-first",
    memoryPolicy: "never-store",
    activeSessionPolicy: "status-only",
  },
  {
    id: "run.explain",
    canonicalName: "解释运行",
    aliases: ["运行 解释", "explain run"],
    surfaces: ALL_SURFACES,
    description: "解释某次运行为什么这样拆解、召回和路由。",
    argsHint: "<runId>",
    outputPolicy: "status-first",
    memoryPolicy: "never-store",
    activeSessionPolicy: "status-only",
  },
  {
    id: "run.audit",
    canonicalName: "审计运行",
    aliases: ["运行 审计", "audit run"],
    surfaces: ["desktop", "cli"],
    description: "查看运行中的权限、工具调用、记忆写入和审查链路。",
    argsHint: "<runId>",
    outputPolicy: "status-first",
    memoryPolicy: "never-store",
    activeSessionPolicy: "status-only",
  },
  {
    id: "run.retry",
    canonicalName: "重试运行",
    aliases: ["运行 重试", "retry run"],
    surfaces: ["desktop", "cli"],
    description: "重试失败或被拒绝的运行步骤。",
    argsHint: "<assignmentId|runId>",
    outputPolicy: "control-reply",
    memoryPolicy: "transient",
    activeSessionPolicy: "execute-now",
  },
  {
    id: "run.approve",
    canonicalName: "批准运行项",
    aliases: ["运行 批准", "批准任务", "approve run"],
    surfaces: ALL_SURFACES,
    description: "批准指定待审 assignment。",
    argsHint: "<assignmentId>",
    outputPolicy: "control-reply",
    memoryPolicy: "transient",
    activeSessionPolicy: "execute-now",
  },
  {
    id: "run.approvePending",
    canonicalName: "批准待审项",
    aliases: ["运行 全部批准", "批准全部", "approve pending"],
    surfaces: ALL_SURFACES,
    description: "批准当前运行中可批量通过的待审项。",
    argsHint: "[runId]",
    outputPolicy: "control-reply",
    memoryPolicy: "transient",
    activeSessionPolicy: "execute-now",
  },
  {
    id: "run.reroute",
    canonicalName: "重路由运行",
    aliases: ["运行 重路由", "reroute run"],
    surfaces: ["desktop", "cli"],
    description: "把运行中的任务重新路由到不同 Skill、工具或适配器。",
    argsHint: "<assignmentId|runId> <目标>",
    outputPolicy: "control-reply",
    memoryPolicy: "transient",
    activeSessionPolicy: "execute-now",
  },
  {
    id: "run.reflect",
    canonicalName: "运行反思",
    aliases: ["运行 反思", "reflect run"],
    surfaces: ["desktop", "cli"],
    description: "对运行结果做复盘，生成可审查改进建议或经验候选。",
    argsHint: "<runId>",
    outputPolicy: "review-gated",
    memoryPolicy: "review-gated-source",
    activeSessionPolicy: "execute-now",
  },
  {
    id: "run.review",
    canonicalName: "审查",
    aliases: ["review", "队列", "运行审查"],
    surfaces: ["desktop", "cli"],
    description: "查看或推进运行与审查队列。",
    argsHint: "[runId|assignmentId]",
    outputPolicy: "status-first",
    memoryPolicy: "never-store",
    activeSessionPolicy: "status-only",
  },
  {
    id: "settings.providers",
    canonicalName: "模型供应方",
    aliases: ["供应方", "api供应方", "模型设置", "API设置", "providers"],
    surfaces: ["desktop", "cli"],
    description: "查看或管理文本、图片等模型供应方。",
    argsHint: "[list|add|set|remove]",
    outputPolicy: "status-first",
    memoryPolicy: "never-store",
    activeSessionPolicy: "status-only",
  },
  {
    id: "settings.provider.set",
    canonicalName: "设置供应方",
    aliases: ["供应方 设置", "设置模型", "set provider"],
    surfaces: ["desktop", "cli"],
    description: "保存供应方 API Key、端点、模型和用途。",
    argsHint: "<provider> <参数>",
    outputPolicy: "control-reply",
    memoryPolicy: "never-store",
    activeSessionPolicy: "execute-now",
  },
  {
    id: "settings.provider.test",
    canonicalName: "测试供应方",
    aliases: ["供应方 测试", "测试模型", "test provider"],
    surfaces: ["desktop", "cli"],
    description: "测试供应方 Key、端点和模型是否可用。",
    argsHint: "<provider|profile>",
    outputPolicy: "status-first",
    memoryPolicy: "never-store",
    activeSessionPolicy: "status-only",
  },
  {
    id: "settings.textModel",
    canonicalName: "文本模型设置",
    aliases: ["设置 文本模型", "text model"],
    surfaces: ["desktop", "cli"],
    description: "设置对话、制作、提炼、审查使用的文本模型。",
    argsHint: "<用途> <model>",
    outputPolicy: "control-reply",
    memoryPolicy: "never-store",
    activeSessionPolicy: "execute-now",
  },
  {
    id: "settings.imageModel",
    canonicalName: "图片模型设置",
    aliases: ["设置 图片模型", "image model"],
    surfaces: ["desktop", "cli"],
    description: "设置图片生成、图片理解或素材预览模型。",
    argsHint: "<用途> <model>",
    outputPolicy: "control-reply",
    memoryPolicy: "never-store",
    activeSessionPolicy: "execute-now",
  },
  {
    id: "settings.switches",
    canonicalName: "功能开关",
    aliases: ["设置 开关", "feature switches"],
    surfaces: ["desktop", "cli"],
    description: "查看或切换运行记忆、经验召回、自我学习入口等功能。",
    argsHint: "[key on|off]",
    outputPolicy: "status-first",
    memoryPolicy: "never-store",
    activeSessionPolicy: "status-only",
  },
  {
    id: "settings.doctor",
    canonicalName: "设置诊断",
    aliases: ["设置 诊断", "settings doctor"],
    surfaces: ["desktop", "cli"],
    description: "检查供应方、存储、桥接、命令和权限设置是否完整。",
    argsHint: "",
    outputPolicy: "status-first",
    memoryPolicy: "never-store",
    activeSessionPolicy: "status-only",
  },
  {
    id: "workspace.status",
    canonicalName: "状态",
    aliases: ["status", "系统状态", "工作区状态", "诊断", "doctor"],
    surfaces: ALL_SURFACES,
    description: "读取当前工作区、通道和后端连接状态。",
    argsHint: "",
    outputPolicy: "status-first",
    memoryPolicy: "never-store",
    activeSessionPolicy: "status-only",
  },
  {
    id: "workspace.settings",
    canonicalName: "设置",
    aliases: ["配置", "settings", "switches"],
    surfaces: ["desktop", "cli"],
    description: "查看或修改本地设置、开关和供应方配置。",
    argsHint: "[参数]",
    outputPolicy: "status-first",
    memoryPolicy: "never-store",
    activeSessionPolicy: "status-only",
  },
  {
    id: "memory.status",
    canonicalName: "记忆",
    aliases: ["memory"],
    surfaces: ALL_SURFACES,
    description: "查看或控制会话记忆与长期记忆状态。",
    argsHint: "[状态|查看|清理]",
    outputPolicy: "status-first",
    memoryPolicy: "never-store",
    activeSessionPolicy: "status-only",
  },
  {
    id: "memory.recallPreview",
    canonicalName: "记忆召回预览",
    aliases: ["记忆 召回", "运行记忆召回", "memory recall"],
    surfaces: ALL_SURFACES,
    description: "按项目、分组、锚点或标签预览会召回哪些运行记忆。",
    argsHint: "<项目|标签|project=...>",
    outputPolicy: "status-first",
    memoryPolicy: "never-store",
    activeSessionPolicy: "status-only",
  },
  {
    id: "maintenance.preview",
    canonicalName: "维护预览",
    aliases: ["维护", "维护 预览", "清理预览", "maintenance", "cleanup preview"],
    surfaces: ALL_SURFACES,
    description: "预览会归档的旧日志、已处理经验候选、隔离记录和低信号资料。",
    argsHint: "[日志保留N|最低分N]",
    outputPolicy: "status-first",
    memoryPolicy: "never-store",
    activeSessionPolicy: "status-only",
  },
  {
    id: "maintenance.apply",
    canonicalName: "执行维护",
    aliases: ["维护 执行", "维护 清理", "清理执行", "maintenance apply", "cleanup"],
    surfaces: ALL_SURFACES,
    description: "归档旧日志和低价值经验资料，并写入维护审计报告。",
    argsHint: "[日志保留N|最低分N]",
    outputPolicy: "control-reply",
    memoryPolicy: "never-store",
    activeSessionPolicy: "execute-now",
  },
  {
    id: "heartbeat.status",
    canonicalName: "心跳状态",
    aliases: ["心跳", "心跳 状态", "学习 状态", "学习状态", "heartbeat"],
    surfaces: ALL_SURFACES,
    description: "查看后台自检、反思和定时整理是否启用。",
    argsHint: "",
    outputPolicy: "status-first",
    memoryPolicy: "never-store",
    activeSessionPolicy: "status-only",
  },
  {
    id: "selfReflection.daily",
    canonicalName: "每日反省",
    aliases: ["反省", "自省", "每日自省", "今日反省", "心跳 反省", "daily reflection"],
    surfaces: ["desktop", "cli"],
    description: "聚合心跳、运行、经验、知识、记忆和维护状态，生成一份只读每日自省报告。",
    argsHint: "[YYYY-MM-DD]",
    outputPolicy: "status-first",
    memoryPolicy: "never-store",
    activeSessionPolicy: "status-only",
  },
  {
    id: "heartbeat.start",
    canonicalName: "启动心跳",
    aliases: ["心跳 启动", "start heartbeat"],
    surfaces: ["desktop", "cli"],
    description: "启动后台心跳任务。",
    argsHint: "",
    outputPolicy: "control-reply",
    memoryPolicy: "never-store",
    activeSessionPolicy: "execute-now",
  },
  {
    id: "heartbeat.stop",
    canonicalName: "停止心跳",
    aliases: ["心跳 停止", "stop heartbeat"],
    surfaces: ["desktop", "cli"],
    description: "停止后台心跳任务。",
    argsHint: "",
    outputPolicy: "control-reply",
    memoryPolicy: "never-store",
    activeSessionPolicy: "interrupt-current",
  },
  {
    id: "soul.status",
    canonicalName: "灵魂状态",
    aliases: ["灵魂", "灵魂 状态", "soul"],
    surfaces: ["desktop", "cli"],
    description: "查看 Director Angel 的身份、原则和能力边界。",
    argsHint: "",
    outputPolicy: "status-first",
    memoryPolicy: "never-store",
    activeSessionPolicy: "status-only",
  },
  {
    id: "soul.view",
    canonicalName: "查看灵魂",
    aliases: ["灵魂 查看", "view soul"],
    surfaces: ["desktop", "cli"],
    description: "查看当前 SOUL 配置全文。",
    argsHint: "",
    outputPolicy: "status-first",
    memoryPolicy: "never-store",
    activeSessionPolicy: "status-only",
  },
];

export function getChannelCommandDefinitions(): readonly ChannelCommandDefinition[] {
  return CHANNEL_COMMAND_REGISTRY;
}

export function getChannelCommandDefinitionsForSurface(
  surface: ChannelCommandSurface,
): readonly ChannelCommandDefinition[] {
  return CHANNEL_COMMAND_REGISTRY.filter((command) => command.surfaces.includes(surface));
}

export function resolveChannelCommandDefinition(nameOrId: string): ChannelCommandDefinition | null {
  const normalized = normalizeCommandName(nameOrId);
  if (normalized.length === 0) {
    return null;
  }
  return (
    CHANNEL_COMMAND_REGISTRY.find(
      (command) =>
        command.id.toLowerCase() === normalized ||
        normalizeCommandName(command.canonicalName) === normalized ||
        command.aliases.some((alias) => normalizeCommandName(alias) === normalized),
    ) ?? null
  );
}

export function parseChannelSlashCommand(text: string): ChannelSlashCommandEnvelope | null {
  const body = text.trim().replace(/^\//u, "").trim();
  if (!text.trim().startsWith("/") || body.length === 0) {
    return null;
  }
  for (const candidate of createSlashCommandCandidates(body)) {
    const command = resolveChannelCommandDefinition(candidate.name);
    if (command !== null) {
      return {
        commandId: command.id,
        canonicalName: command.canonicalName,
        matchedName: candidate.name,
        args: candidate.args,
        outputPolicy: command.outputPolicy,
        memoryPolicy: command.memoryPolicy,
        activeSessionPolicy: command.activeSessionPolicy,
      };
    }
  }
  return null;
}

export function shouldBypassActiveSession(commandIdOrName: string): boolean {
  const command = resolveChannelCommandDefinition(commandIdOrName);
  return (
    command?.activeSessionPolicy === "execute-now" ||
    command?.activeSessionPolicy === "interrupt-current" ||
    command?.activeSessionPolicy === "status-only"
  );
}

function normalizeCommandName(value: string): string {
  return value.trim().replace(/^\//u, "").replace(/\s+/gu, " ").toLowerCase();
}

function createSlashCommandCandidates(body: string): Array<{ name: string; args: string }> {
  const tokenMatches = [...body.matchAll(/\S+/gu)];
  const candidates: Array<{ name: string; args: string }> = [];
  for (let tokenCount = Math.min(3, tokenMatches.length); tokenCount >= 1; tokenCount -= 1) {
    const lastToken = tokenMatches[tokenCount - 1];
    const endIndex = (lastToken?.index ?? 0) + (lastToken?.[0]?.length ?? 0);
    candidates.push({
      name: body.slice(0, endIndex).trim().replace(/\s+/gu, " "),
      args: body.slice(endIndex).trim(),
    });
  }
  return candidates;
}
